### ISSUE TITLE
exit status codes

### ISSUE THREAD

**Issue by tbuser** [makerbot/conveyor#14]
Feature request: when called in linux, return standard exit status codes on success/failure.

**Comment by martymcguire** [comment]
:+1:

(... +1s are helpful and totally not annoying)

**Comment by msamsonoff** [comment]
I'm actually going to mark this as a bug instead of an enhancement. We've taken great care to wire up conveyor internally so that it can return proper exit codes, but then every module just returns "1" for every error.

**Comment by tbuser** [comment]
I see some mention of this in the commit history, has this been fixed and should I re-test this?

**Comment by msamsonoff** [comment]
We've fixed up some places, but we don't have standard codes everywhere. Still pending.

**Comment by msamsonoff** [comment]
Fixed.
