### ISSUE TITLE
invalid json in manifests with empty arrays

### ISSUE THREAD

**Issue by tbuser** [makerbot/conveyor#15]
The proper syntax for an empty array in json is [] however if conveyor encounters this in a thing manifest, such as line 2 of:

{
  "namespace": "http://spec.makerbot.com/ns/thing.0.1.1.1", 
  "objects": { "bunny.stl": [] }, 
  "instances": { 
    "bunny": { 
      "object": "bunny.stl", 
      "scale": "mm"
    }
  }
}

it fails saying:

./conveyor -c conveyor-ReplicatorDual-skeinforge.conf slice test_thing foo.gcode
conveyor: INFO: slicing to file: test_thing -> foo.gcode
conveyor: ERROR: task failed: {u'message': u'uncaught exception', u'code': -32000, u'data': {u'message': u'', u'args': [], u'name': u'Exception'}}
conveyor: ERROR: conveyor terminating with status code 1

The example thing manifests have empty arrays as {} which works, but {} is for empty objects which isn't what I would expect.

**Comment by msamsonoff** [comment]
The value associated with "bunny.stl" should be a JSON object, not an array. It holds key/value pairs of data associated with the object (although we don't currently have any key/values defined). Values under "objects" work the same way as values under "instances" where we have defined several standard keys.

Take a look at the examples in conveyor/doc/MBI-RFC-03-Thing_File_Format-DRAFT.md (which are also under conveyor/src/test/thing/).
