### ISSUE TITLE
conveyor hangs if conveyord is not running or an error is enountered

### ISSUE THREAD

**Issue by tbuser** [makerbot/conveyor#2]
If conveyord is not running and I run for instance:

./conveyor -c conveyor-skeinforge.conf slice src/test/thing/rfc-5.4 /home/thingiv3rse/test.gcode

I get:

conveyor: CRITICAL: failed to open socket: unix:conveyord.socket: No such file or directory
conveyor: ERROR: conveyor terminating with status code 1

and conveyor locks up and does not return.  I'd expect it to stop and return that error instead of just printing the message and staying running.  Incidentially pressing ctrl-c does not stop it.  Only way to stop it is to kill -9 it.

**Comment by tbuser** [comment]
This happens weather or not I source virtualenv first.

**Comment by tbuser** [comment]
It also causes the conveyor client process to hang if conveyord hits an error.

**Comment by msamsonoff** [comment]
Fixed.
