### ISSUE TITLE
skeinforge currently broken in master

### ISSUE THREAD

**Issue by tbuser** [makerbot/conveyor#20]
The replicator profile inserts M105 which has been removed from s3g.

...
2012-07-27 17:44:53,950 - INFO - gcode: '(<extruderInitialization>)'
2012-07-27 17:44:53,950 - INFO - gcode: '(<craftTypeName> extrusion </craftTypeName>)'
2012-07-27 17:44:53,951 - INFO - gcode: 'M105'
2012-07-27 17:44:53,951 - ERROR - {"event":"unrecognized_command", "command":105}
2012-07-27 17:44:53,951 - ERROR - {"event":"gcode_error"}
2012-07-27 17:44:53,951 - ERROR - unhandled exception
Traceback (most recent call last):
  File "./src/main/python/conveyor/printer/s3g.py", line 140, in runningcallback
    self._genericprint(task, writer, False, gcodepath, skip_start_end)
  File "./src/main/python/conveyor/printer/s3g.py", line 87, in _genericprint
    parser.execute_line(data)
  File "./submodule/s3g/s3g/Gcode/parser.py", line 118, in execute_line
    raise gcode_error
UnrecognizedCommandError: UnrecognizedCommand: 105; Command: M105; LineNumber: 33

**Comment by dgs3** [comment]
There is actually a preprocessor that needs to be run on gcode files
skeined with skeinforge.  The preprocessor itself is in
/s3g/Preprocessors/.

I made a script that makes it (fairly) painless to process these files
named process_sf_file.py in /examples/.  It takes some command line
arguments to run:
- -i <input file>
- -o <output file>
- -s <version of skeinforge, as an int>

Once the file is processed it should run fine.

Conveyor should have the functionality to preprocess files, but its
currently broken.  Once I get some free cycles I'll attempt to mend it.

On 27 July 2012 13:52, Tony Buser <
reply@reply.github.com

> wrote:
> 
> The replicator profile inserts M105 which has been removed from s3g.
> 
> ...
> 2012-07-27 17:44:53,950 - INFO - gcode: '(<extruderInitialization>)'
> 2012-07-27 17:44:53,950 - INFO - gcode: '(<craftTypeName> extrusion
> </craftTypeName>)'
> 2012-07-27 17:44:53,951 - INFO - gcode: 'M105'
> 2012-07-27 17:44:53,951 - ERROR - {"event":"unrecognized_command",
> "command":105}
> 2012-07-27 17:44:53,951 - ERROR - {"event":"gcode_error"}
> 2012-07-27 17:44:53,951 - ERROR - unhandled exception
> Traceback (most recent call last):
>   File "./src/main/python/conveyor/printer/s3g.py", line 140, in
> runningcallback
>     self._genericprint(task, writer, False, gcodepath, skip_start_end)
>   File "./src/main/python/conveyor/printer/s3g.py", line 87, in
> _genericprint
>     parser.execute_line(data)
>   File "./submodule/s3g/s3g/Gcode/parser.py", line 118, in execute_line
>     raise gcode_error
> UnrecognizedCommandError: UnrecognizedCommand: 105; Command: M105;
> LineNumber: 33
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/makerbot/conveyor/issues/20

## 

dgs3

**Comment by tbuser** [comment]
Ah, thanks.  That works.  Although it would be nice, since I already told conveyor to use skeinforge, that this pre-processing be done automatically instead of needing to be run as another process.  :)

**Comment by msamsonoff** [comment]
We have to change the skeinforge slicing recipes to request tihs preprocessor. And then we have to fix the confusion in the code about whether or not the value is a string or a function.

**Comment by msamsonoff** [comment]
Fixed.

**Comment by tbuser** [comment]
Does that mean the preprocessor will run automatically now?

**Comment by msamsonoff** [comment]
Yes. It will automatically use the Skeinforge preprocessor for Skeinforge jobs.
