### ISSUE TITLE
Background service not available

### ISSUE THREAD

**Issue by robertcedwards** [makerbot/conveyor#23]
Installed new Makerware (MakerWare 2.1.0)
Can't seem to kill or start the process…
2013-05-15 14:44:31,458 - ERROR - pid file exists: /var/tmp/conveyord.pid
2013-05-15 14:44:31,458 - ERROR - conveyord terminating with exit code 1

**Comment by robertcedwards** [comment]
Some more of the logs today…

`5/16/13 8:46:06.513 AM com.apple.launchd[1]: (com.makerbot.conveyor.daemon[7128]) Exited with code: 1
5/16/13 8:46:06.513 AM com.apple.launchd[1]: (com.makerbot.conveyor.daemon) Throttling respawn: Will start in 10 seconds
5/16/13 8:46:06.000 AM kernel[0]: CODE SIGNING: cs_invalid_page(0x103ee4000): p=7128[python] clearing CS_VALID
5/16/13 8:46:16.000 AM kernel[0]: CODE SIGNING: cs_invalid_page(0x1096d1000): p=7134[python] clearing CS_VALID
5/16/13 8:46:16.733 AM com.apple.launchd[1]: (com.makerbot.conveyor.daemon[7134]) Exited with code: 1`

**Comment by AKAMEDIASYSTEM** [comment]
I had this issue and was able to resolve it by just going to /var/tmp/ and deleting conveyorid.pid and some conveyor-related .socket file I saw.

Doesn't mean this issue should exist, though, so I guess the ticket should remain open.

**Comment by robertcedwards** [comment]
#25 Solved it for me…
