### ISSUE TITLE
VirtualEnv on Macs/Git?

### ISSUE THREAD

**Issue by nmsl1993** [makerbot/conveyor#9]
On an OSX laptop with python 2.6 when I tried to pull from git and run the setup.sh the shell script terminated saying "activate: command not found." Git said it was up to date with 6b42bddc, however the contents of virtualenv/bin directory only contained pip and python 2.7 rather than all the files that should be in that directory as of 6b42bddc.

**Comment by msamsonoff** [comment]
Sometimes the virtualenv directory gets messed up. We should add to HACKING.md some text about removing and rebuilding it. Developers should do this periodically.
